[package]
name = "pong"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console =  { git = "https://github.com/goodartistscopy/console", branch = "patch-1", default-features = false }
rand = "0.8.5"